# Generated by Django 4.2.1 on 2023-05-28 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='lugar_residencia',
            new_name='ciudad',
        ),
    ]
